updates:
  - allow:
      - dependency-type: 'direct'
    commit-message:
      include: 'scope'
      prefix: 'fix'
    directory: '/'
    open-pull-requests-limit: 99
    package-ecosystem: 'github-actions'
    reviewers:
      - '@softcrumhq/architecture'
    schedule:
      interval: 'daily'
      time: '06:00'
    target-branch: 'develop'
  - allow:
      - dependency-type: 'direct'
    commit-message:
      include: 'scope'
      prefix: 'fix'
    directory: '/'
    open-pull-requests-limit: 99
    package-ecosystem: 'npm'
    reviewers:
      - '@softcrumhq/architecture'
    schedule:
      interval: 'daily'
      time: '06:00'
    target-branch: 'develop'
    versioning-strategy: 'increase'
version: 2
