name: Pipeline Changelog

on:
  registry_package:
    types: [published, updated]

jobs:
  changelog:
    name: Changelog [NodeJS ${{ matrix.node-version }}, OS ${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['14.x']
        os: [ubuntu-latest]
    steps:
    - name: Run script - git checkout
      uses: actions/checkout@v2
    - name: Run script - setup
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@softcrumhq'
    - name: Run script - install
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Run script - changelog
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: changelog
    - name: Run script - gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        git-commit-gpgsign: true
        gpg-private-key: ${{ secrets.GPG_KEY }}
        git-user-signingkey: true
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - name: Run script - commit changes
      run: |
            git add -A
            git commit -S -m "chore(changelog): Update CHANGELOG.md"
            git push
    timeout-minutes: 5
