name: Pipeline Release

on:
  push:
    branches:
      - release
      - develop

jobs:
  release:
    if: contains(github.event.commits[0].message, 'chore(release)') == false
    name: Release [NodeJS ${{ matrix.node }}, OS ${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]
    steps:
    - name: Run script - git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run script - setup
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@softcrumhq'
    - name: Run script - release
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB }}
      uses: ridedott/release-me-action@master
      with:
        release-branches:
          '[
            "+([0-9])?(.{+([0-9]),x}).x",
            "master",
            { "name": "alpha", "prerelease": "alpha" },
            { "name": "beta", "prerelease": "beta" },
            { "name": "develop", "prerelease": "build" },
            { "name": "release", "prerelease": "rc" }
          ]'
        release-rules:
          '[
            { "type": "breaking", "release": "major" },
            { "type": "bugfix", "release": "minor" },
            { "type": "chore(changelog)", "release": false },
            { "type": "chore(deps)", "release": "patch" },
            { "type": "chore(deps-dev)", "release": "patch" },
            { "type": "feature", "release": "minor" },
            { "type": "hotfix", "release": "patch" },
            { "type": "security", "release": "patch" }
          ]'
        disable-changelog: true
        disable-generate-changelog: true
    timeout-minutes: 5
